---
title: Standard ECMA-55 - Minimal BASIC
description: Electronic version of the scanned original

timezone: Europa/Paris

theme: jekyll-theme-hacker

static_files:
- _static/

remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # added for hacker theme
- jekyll-avatar
- jekyll-feed
- jekyll-mentions
- jekyll-redirect-from
- jekyll-seo-tag
- jekyll-sitemap
- jemoji
